[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://hoppermedia.tv/*"
  to = "https://www.hoppermedia.tv/:splat"
  status = 301
  force = true